function(aeolion_add_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE aeolion)
    add_test(NAME ${name} COMMAND ${name})
endfunction()

aeolion_add_test(TestVLMCore)
aeolion_add_test(TestBEMT)
aeolion_add_test(TestPropVane)
aeolion_add_test(TestSolverBackend)
