#!/usr/bin/env python3
"""Generate the report's data tables from the solver's own JSON.

The house rule: no number in a published document is typed by hand. This
reads models/data/propulsion-map.json (written by aeolion_propulsion_map)
and emits LaTeX table fragments into models/report/tables/, which
report.tex \\input's.

Usage:  python make-tables.py [path/to/propulsion-map.json]
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_JSON = os.path.join(HERE, "..", "data", "propulsion-map.json")
OUT_DIR = os.path.join(HERE, "tables")

# Modes carry a nonzero deflection; the baseline row is delta = 0.
MODE_LABELS = {"pitch": "Pitch", "yaw": "Yaw", "roll": "Roll"}


def load(path):
    with open(path, "r") as handle:
        doc = json.load(handle)
    return doc["meta"], doc["rows"]


def fmt(value, digits=4):
    """Fixed-point, with a true zero written plainly rather than -0.0000."""
    if abs(value) < 0.5 * 10 ** (-digits):
        return "0"
    return f"{value:.{digits}f}"


def baseline_table(meta, rows, out):
    """CT, CQ and the wrench along the advance-ratio axis, vanes neutral."""
    base = sorted([r for r in rows if r["mode"] == "baseline"], key=lambda r: r["J"])
    if not base:
        return False

    with open(out, "w") as f:
        f.write("% GENERATED by make-tables.py -- do not edit.\n")
        f.write("\\begin{table}[htbp]\n\\centering\n")
        f.write(
            "\\caption{Generated propulsor baseline: the contract's ducted fan at "
            f"$n = {meta['revsPerSec']:.1f}$~rev/s "
            f"($\\Omega = {meta['omegaRadps']:.0f}$~rad/s), $D = {meta['diameterM']:.4f}$~m, "
            f"{meta['bladeCount']} blades, $\\rho = {meta['rho']}$~kg/m$^3$, vanes neutral. "
            "Forces and moments in FRD about the contract's moment reference point. "
            "$Q$ is the shaft torque, i.e. the jet's angular-momentum flux.}\n"
        )
        f.write("\\label{tab:propbaseline}\n")
        f.write("\\begin{tabular}{@{}rrrrrrrr@{}}\n\\toprule\n")
        f.write(
            "$J$ & $V_\\infty$ & $T$ & $Q$ & $C_T$ & $C_Q$ & $M_x$ & conv. \\\\\n"
            " & [m/s] & [N] & [N\\,m] & & & [N\\,m] & \\\\\n"
        )
        f.write("\\midrule\n")
        for r in base:
            f.write(
                f"{r['J']:.2f} & {r['VinfMps']:.2f} & {r['thrustN']:.3f} & "
                f"{r['jetTorqueNm']:.4f} & {r['ct']:.4f} & {r['cq']:.5f} & "
                f"{fmt(r['totalFrd']['mx'], 4)} & "
                f"{'yes' if r['converged'] else 'NO'} \\\\\n"
            )
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    return True


def mode_table(meta, rows, out):
    """Vane-mode increments from the neutral baseline at matched J."""
    baseline = {r["J"]: r for r in rows if r["mode"] == "baseline"}
    modes = [m for m in ("pitch", "yaw", "roll") if any(r["mode"] == m for r in rows)]
    if not modes or not baseline:
        return False

    # Report at the soft limit, the largest command an allocator may use.
    limit = max((abs(r["deltaDeg"]) for r in rows if r["mode"] != "baseline"), default=0.0)
    picked = sorted(
        [r for r in rows if r["mode"] != "baseline" and abs(r["deltaDeg"] - limit) < 1e-9],
        key=lambda r: (r["mode"], r["J"]),
    )
    if not picked:
        return False

    with open(out, "w") as f:
        f.write("% GENERATED by make-tables.py -- do not edit.\n")
        f.write("\\begin{table}[htbp]\n\\centering\n")
        f.write(
            f"\\caption{{Generated vane-mode increments at the $+{limit:.0f}^\\circ$ soft "
            "limit, taken from the neutral baseline at matched advance ratio. Each mode "
            "carries a full wrench: the off-axis components are the rotor swirl's "
            "signature, not numerical noise. $\\Delta Q$ is the back-pressure on the "
            "shaft, which exists because the rotor--vane coupling is two-way.}\n"
        )
        f.write("\\label{tab:propmodes}\n")
        f.write("\\begin{tabular}{@{}llrrrrrrr@{}}\n\\toprule\n")
        f.write(
            "Mode & $J$ & $\\Delta F_x$ & $\\Delta F_y$ & $\\Delta F_z$ & "
            "$\\Delta M_x$ & $\\Delta M_y$ & $\\Delta M_z$ & $\\Delta Q$ \\\\\n"
            " & & [N] & [N] & [N] & [N\\,m] & [N\\,m] & [N\\,m] & [N\\,m] \\\\\n"
        )
        f.write("\\midrule\n")
        current = None
        for r in picked:
            b = baseline.get(r["J"])
            if b is None:
                continue
            label = MODE_LABELS[r["mode"]] if r["mode"] != current else ""
            if r["mode"] != current and current is not None:
                f.write("\\addlinespace\n")
            current = r["mode"]
            d = {k: r["totalFrd"][k] - b["totalFrd"][k] for k in r["totalFrd"]}
            dq = r["jetTorqueNm"] - b["jetTorqueNm"]
            f.write(
                f"{label} & {r['J']:.2f} & {fmt(d['fx'],3)} & {fmt(d['fy'],3)} & "
                f"{fmt(d['fz'],3)} & {fmt(d['mx'],4)} & {fmt(d['my'],4)} & "
                f"{fmt(d['mz'],4)} & {fmt(dq,4)} \\\\\n"
            )
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    return True


WRENCH_KEYS = ["fx", "fy", "fz", "mx", "my", "mz"]
# Moments are an order smaller in magnitude than forces on this vehicle, so
# a plain 6-vector norm would let force error swamp moment error. The
# moment terms are weighted by a nominal 10 1/m so both register.
MOMENT_WEIGHT = 10.0


def _weighted_norm(vec):
    return sum(x * x for x in vec[:3]) ** 0.5 + MOMENT_WEIGHT * sum(x * x for x in vec[3:]) ** 0.5


def superposition_table(sup_path, base_rows, out):
    """Pair commands against the sum of their single-mode increments."""
    if not os.path.exists(sup_path):
        return False
    with open(sup_path, "r") as handle:
        sup = json.load(handle)["rows"]

    base = {round(r["J"], 3): r for r in base_rows if r["mode"] == "baseline"}
    idx = {(r["mode"], round(r["deltaDeg"], 2), round(r["J"], 3)): r for r in sup}
    pairs = [("pitch+yaw", "pitch", "yaw"), ("pitch+roll", "pitch", "roll"),
             ("yaw+roll", "yaw", "roll")]
    deltas = sorted({round(r["deltaDeg"], 2) for r in sup if r["deltaDeg"] > 0})
    js = sorted({round(r["J"], 3) for r in sup})

    lines, worst = [], (0.0, "")
    for pair, m1, m2 in pairs:
        for delta in deltas:
            for j in js:
                p = idx.get((pair, delta, j))
                a = idx.get((m1, delta, j))
                b = idx.get((m2, delta, j))
                bs = base.get(j)
                if not all((p, a, b, bs)):
                    continue
                dp = [p["totalFrd"][k] - bs["totalFrd"][k] for k in WRENCH_KEYS]
                da = [a["totalFrd"][k] - bs["totalFrd"][k] for k in WRENCH_KEYS]
                db = [b["totalFrd"][k] - bs["totalFrd"][k] for k in WRENCH_KEYS]
                err = [dp[i] - da[i] - db[i] for i in range(6)]
                mag, emag = _weighted_norm(dp), _weighted_norm(err)
                rel = 100.0 * emag / max(mag, 1e-12)
                lines.append((pair.replace("+", "{+}"), delta, j, mag, emag, rel))
                if rel > worst[0]:
                    worst = (rel, f"{pair} at ${delta:+.1f}^\\circ$, $J = {j:.1f}$")

    if not lines:
        return False

    with open(out, "w") as f:
        f.write("% GENERATED by make-tables.py -- do not edit.\n")
        f.write("\\begin{table}[htbp]\n\\centering\n")
        f.write(
            "\\caption{Measured superposition error of the vane command modes: each "
            "simultaneous pair against the sum of its two single-mode increments, both "
            "taken from the neutral baseline at matched advance ratio. Magnitudes are "
            f"$\\|F\\| + {MOMENT_WEIGHT:.0f}\\,\\|M\\|$ so that moment error is not "
            "swamped by force error. Pitch and yaw superpose; anything involving roll "
            "does not.}\n"
        )
        f.write("\\label{tab:superposition}\n")
        f.write("\\begin{tabular}{@{}lrrrrr@{}}\n\\toprule\n")
        f.write(
            "Pair & $\\delta$ [deg] & $J$ & combined & error & relative \\\\\n"
            "\\midrule\n"
        )
        last = None
        for pair, delta, j, mag, emag, rel in lines:
            if last is not None and pair != last:
                f.write("\\addlinespace\n")
            label = pair if pair != last else ""
            last = pair
            f.write(
                f"{label} & {delta:+.1f} & {j:.2f} & {mag:.4f} & {emag:.4f} "
                f"& {rel:.2f}\\% \\\\\n"
            )
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    print(f"  worst superposition error {worst[0]:.1f}% ({worst[1]})")
    return True


def aileron_table(path, out):
    """Aileron increments against incidence, at one representative command."""
    if not os.path.exists(path):
        return False
    with open(path, "r") as handle:
        doc = json.load(handle)
    rows = doc.get("aileron", [])
    if not rows:
        return False
    idx = {(r["alphaDeg"], r["deltaDeg"]): r for r in rows}
    probe = 10.0
    show = [0, 6, 12, 18, 20, 26, 30, 45, 60, 90]
    picked = [idx[(float(a), probe)] for a in show if (float(a), probe) in idx]
    if not picked:
        return False
    ref = abs(picked[0]["dCl"]) or 1.0

    with open(out, "w") as f:
        f.write("% GENERATED by make-tables.py -- do not edit.\n")
        f.write("\\begin{table}[htbp]\n\\centering\n")
        f.write(
            "\\caption{Aileron increments at $\\delta_a = +%g^\\circ$ from the generated "
            "sweep. Roll authority collapses through stall while adverse yaw grows, so past "
            "$\\alpha \\approx 30^\\circ$ the surface produces mostly yaw -- and its rolling "
            "moment is small enough that its sign is not resolved. Daggered rows are "
            "limit-cycle means, not steady states.}\n" % probe
        )
        f.write("\\label{tab:aileronsweep}\n")
        f.write("\\begin{tabular}{@{}rrrrl@{}}\n\\toprule\n")
        f.write(
            "$\\alpha$ [deg] & $\\Delta C_l$ & $\\Delta C_n$ & retained & "
            "$|\\Delta C_n / \\Delta C_l|$ \\\\\n\\midrule\n"
        )
        for r in picked:
            ratio = abs(r["dCn"] / r["dCl"]) if r["dCl"] else float("nan")
            f.write(
                "%g & %+.6f & %+.6f & %.0f\\%% & %.2f%s \\\\\n"
                % (r["alphaDeg"], r["dCl"], r["dCn"], 100 * abs(r["dCl"]) / ref, ratio,
                   "" if r["converged"] else " $^{\\dagger}$")
            )
        f.write("\\bottomrule\n\\end{tabular}\n")
        f.write("\\\\[1mm]\\footnotesize $^{\\dagger}$ limit-cycle mean.\n")
        f.write("\\end{table}\n")

    tau = doc.get("aileronTau")
    print(f"  aileron: tau = {tau:.4f}, authority retained "
          f"{100*abs(picked[-1]['dCl'])/ref:.0f}% at alpha 90")
    return True


def parasite_table(path, out):
    """Component buildup plus the crossflow branch over the alpha grid."""
    if not os.path.exists(path):
        return False
    with open(path, "r") as handle:
        doc = json.load(handle)
    meta, comps, table = doc["meta"], doc["components"], doc["table"]
    # A representative subset of the alpha grid: the table itself is long
    # and its shape is carried by sin^3.
    show = [0.0, 4.0, 8.0, 12.0, 16.0, 20.0, 30.0, 45.0, 60.0, 90.0]
    rows = [r for r in table if any(abs(r["alphaDeg"] - a) < 1e-9 for a in show)]

    with open(out, "w") as f:
        f.write("% GENERATED by make-tables.py -- do not edit.\n")
        f.write("\\begin{table}[htbp]\n\\centering\n")
        f.write(
            "\\caption{Parasite drag of the body and duct, referred to the wing "
            f"reference area $S = {meta['Sref']:.4f}$~m$^2$ at $V_\\infty = "
            f"{meta['Vinf']:.0f}$~m/s. Upper block: the component buildup. Lower "
            "block: the total against incidence, Eq.~\\eqref{eq:cd0}. The wing is "
            "absent by design---its profile drag is already inside the force "
            "tables.}\n"
        )
        f.write("\\label{tab:parasite}\n")
        f.write("\\begin{tabular}{@{}lrrrrr@{}}\n\\toprule\n")
        f.write(
            "Component & $S_{\\mathrm{wet}}$ [m$^2$] & $Re$ & $C_f$ & $FF$ & "
            "$C_{D_0}$ \\\\\n\\midrule\n"
        )
        for c in comps:
            mantissa, exponent = f"{c['Re']:.2e}".split("e")
            re_tex = f"${mantissa} \\times 10^{{{int(exponent)}}}$"
            f.write(
                f"{c['name']} & {c['Swet']:.4f} & {re_tex} & {c['Cf']:.5f} & "
                f"{c['FF']:.3f} & {c['CD0']:.5f} \\\\\n"
            )
        f.write(
            f"\\midrule\n\\multicolumn{{5}}{{@{{}}l}}{{friction total, "
            f"incl. {100*meta['miscFraction']:.0f}\\% excrescence allowance}} & "
            f"{meta['CD0friction']:.5f} \\\\\n"
        )
        f.write("\\midrule\n")
        f.write(
            "$\\alpha$ [deg] & \\multicolumn{2}{r}{friction} & "
            "\\multicolumn{2}{r}{crossflow} & $C_{D_0}$ \\\\\n\\midrule\n"
        )
        for r in rows:
            f.write(
                f"{r['alphaDeg']:.0f} & \\multicolumn{{2}}{{r}}{{{r['CD0friction']:.5f}}} & "
                f"\\multicolumn{{2}}{{r}}{{{r['CD0crossflow']:.5f}}} & {r['CD0']:.5f} \\\\\n"
            )
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    ratio = meta["crossflowCoeff"] / max(meta["CD0friction"], 1e-12)
    print(f"  parasite: CD0(90 deg) = {meta['CD0friction']+meta['crossflowCoeff']:.4f}"
          f" ({ratio:.1f}x the friction term)")
    return True


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_JSON
    if not os.path.exists(path):
        print(f"no map at {path} -- run aeolion_propulsion_map first", file=sys.stderr)
        return 1
    meta, rows = load(path)
    os.makedirs(OUT_DIR, exist_ok=True)

    wrote = []
    if baseline_table(meta, rows, os.path.join(OUT_DIR, "propulsion-baseline.tex")):
        wrote.append("propulsion-baseline.tex")
    if mode_table(meta, rows, os.path.join(OUT_DIR, "propulsion-modes.tex")):
        wrote.append("propulsion-modes.tex")
    ail_path = os.path.join(os.path.dirname(path), "aero-aileron.json")
    if aileron_table(ail_path, os.path.join(OUT_DIR, "aileron.tex")):
        wrote.append("aileron.tex")
    par_path = os.path.join(os.path.dirname(path), "parasite-drag.json")
    if parasite_table(par_path, os.path.join(OUT_DIR, "parasite.tex")):
        wrote.append("parasite.tex")
    sup_path = os.path.join(os.path.dirname(path), "propulsion-superposition.json")
    if superposition_table(sup_path, rows, os.path.join(OUT_DIR, "superposition.tex")):
        wrote.append("superposition.tex")

    unconverged = sum(1 for r in rows if not r["converged"])
    print(f"{len(rows)} rows read ({unconverged} unconverged); wrote {', '.join(wrote)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
